var Phaser=Phaser||{},Platformer=Platformer||{};Platformer.BootState=function(){Phaser.State.call(this)};Platformer.prototype=Object.create(Phaser.State.prototype);Platformer.prototype.constructor=Platformer.BootState;Platformer.BootState.prototype.init=function(a){this.levelName=a};
Platformer.BootState.prototype.preload=function(){this.load.text("Level 1","assets/levels/Level 1.json");this.load.text("Level 2","assets/levels/Level 2.json");this.load.text("Level 3","assets/levels/Level 3.json");this.load.text("Level 4","assets/levels/Level 4.json");this.load.text("Level 5","assets/levels/Level 5.json");this.load.text("Level 6","assets/levels/Level 6.json");this.load.text("Level 7","assets/levels/Level 7.json");this.load.text("Level 8","assets/levels/Level 8.json");this.load.text("Level 9",
"assets/levels/Level 9.json")};
Platformer.BootState.prototype.create=function(){if(this.levelName&&"menu"!==this.levelName)this.loadLevel({name:this.levelName});else if("menu"===this.levelName)this.createMenu();else{var a=this.add.sprite(0,0,"background");a.width=this.game.width;a.height=this.game.height;a.smoothed=!1;this.logo=this.add.image(this.game.width/2,this.game.height/2,"logo");this.logo.scale.setTo(.8,.8);this.logo.anchor.setTo(.5,.5);a=this.game.make.text(0,200,"Click to start",{font:"Verdana",fontSize:"50px",fill:"#ffffff"});
a.anchor.setTo(.5,0);this.logo.addChild(a);this.blinking=this.time.events.loop(300,this.blink,this,a);myGame.input.onDown.add(this.startGame,this)}};Platformer.BootState.prototype.blink=function(a){a.alive?a.alpha=1===a.alpha?0:1:this.time.events.remove(this.blinking)};Platformer.BootState.prototype.loadLevel=function(a){a=this.game.cache.getText(a.name);a=JSON.parse(a);myGame.state.start("LoadingState",!0,!1,a)};
Platformer.BootState.prototype.loadShop=function(){myGame.state.start("ShopMenu",!0,!1)};Platformer.BootState.prototype.loadSettings=function(){myGame.state.start("SettingsMenu",!0,!1)};
Platformer.BootState.prototype.startGame=function(){myGame.input.onDown.removeAll();this.logo.children[0].kill();var a=this.add.tween(this.logo.scale);a.to({x:.3,y:.3},1E3,Phaser.Easing.Linear.None);var b=this.add.tween(this.logo.position);b.to({x:150,y:60},1E3,Phaser.Easing.Linear.None);a.onComplete.addOnce(this.createMenu,this);a.start();b.start()};
Platformer.BootState.prototype.createMenu=function(){var a=this.add.sprite(0,0,"background");a.width=this.game.width;a.height=this.game.height;a.smoothed=!1;this.logo=this.add.image(150,60,"logo");this.logo.scale.setTo(.3,.3);this.logo.anchor.setTo(.5,.5);this.game.add.text(this.game.width/2,125,"Menu",{font:"Verdana",fontSize:"32px",fill:"#ffffff"}).anchor.setTo(.5,.5);a=this.game.add.button(this.game.width/2+125,60,"button",this.loadShop,this,0,1,2);a.anchor.setTo(.5,.5);a.scale.setTo(.8,.8);var b=
{font:"Verdana",fontSize:"32px",fill:"#ffffff"},c=this.game.make.text(0,0,"Shop",b);c.anchor.setTo(.5,.5);a.addChild(c);a=this.game.add.button(this.game.width/2+275,60,"button",this.loadSettings,this,0,1,2);a.anchor.setTo(.5,.5);a.scale.setTo(.8,.8);c=this.game.make.text(0,0,"Settings",b);c.anchor.setTo(.5,.5);a.addChild(c);var d,e=0,f=0;for(d=0;9>d;d++)contains(userGameData.levelsUnlocked,d+1+"")?(c="Level "+(d+1),a=this.game.add.button(200+200*f,220+100*e,"button",this.loadLevel,this,0,1,2),a.name=
c,a.anchor.setTo(.5,.5),c=this.game.make.text(0,0,a.name,b),c.anchor.setTo(.5,.5),a.addChild(c)):(a=this.game.add.image(200+200*f,220+100*e,"disabledButton"),a.anchor.setTo(.5,.5)),0===(d+1)%3?(e+=1,f=0):f+=1};Phaser=Phaser||{};Platformer=Platformer||{};Platformer.LoadingState=function(){Phaser.State.call(this)};Platformer.prototype=Object.create(Phaser.State.prototype);Platformer.prototype.constructor=Platformer.LoadingState;Platformer.LoadingState.prototype.init=function(a){this.level_data=a;this.loadingText=0};Platformer.LoadingState.prototype.preload=function(){this.load.image("background","assets/images/sky.png");this.load.image("logo","assets/images/Logo4.png")};
Platformer.LoadingState.prototype.startLoading=function(){var a,b,c;a=this.level_data.assets;for(b in a)if(a.hasOwnProperty(b))switch(c=a[b],c.type){case "image":this.load.image(b,c.source);break;case "spritesheet":this.load.spritesheet(b,c.source,c.frame_width,c.frame_height,c.frames,c.margin,c.spacing);break;case "tilemap":this.load.tilemap(b,c.source,null,Phaser.Tilemap.TILED_JSON);break;case "atlas":this.load.atlas(b,c.image,c.json)}this.load.start()};
Platformer.LoadingState.prototype.startLoadingMenu=function(){this.load.spritesheet("button","assets/images/button.png",145,45);this.load.image("disabledButton","assets/images/DisabledButton.png");this.load.image("disabledShopButton","assets/images/DisabledShopButton.png");this.load.spritesheet("shopButton","assets/images/ShopButton.png",100,200);this.load.spritesheet("hearth","assets/images/ui/hearth.png",35,33);this.load.spritesheet("mana","assets/images/ui/mana.png",32,32);this.load.spritesheet("fireball",
"assets/images/player/fireball.png",50,22);this.load.image("waterball","assets/images/player/snowflake2.png");this.load.start()};
Platformer.LoadingState.prototype.create=function(){var a=this.add.sprite(0,0,"background");a.width=this.game.width;a.height=this.game.height;a.smoothed=!1;a=this.add.image(this.game.width/2,this.game.height/2,"logo");a.scale.setTo(.8,.8);a.anchor.setTo(.5,.5);this.load.onFileComplete.add(this.fileComplete,this);this.load.onLoadComplete.add(this.loadComplete,this);this.loadingText=this.add.text(this.game.width/2,a.bottom+50,"Loading ...",{fill:"#ffffff"});this.loadingText.anchor.setTo(.5,.5);"menu"===
this.level_data?this.startLoadingMenu():this.startLoading()};Platformer.LoadingState.prototype.fileComplete=function(a,b,c,d,e){this.loadingText.setText("Loading ... "+a+"% ")};Platformer.LoadingState.prototype.loadComplete=function(){this.loadingText.setText("Load Complete");setTimeout(function(a){"menu"===a.level_data?myGame.state.start("BootState",!0,!1):myGame.state.start("TiledState",!0,!1,a.level_data)},500,this)};
Platformer.LoadingState.prototype.shutdown=function(){Phaser.State.prototype.shutdown.call(this);this.load.onLoadComplete.removeAll();this.load.onFileComplete.removeAll()};Phaser=Phaser||{};Platformer=Platformer||{};
Platformer.PauseMenu=function(a,b,c){var d=[];switch(b){case thirdButton.RESUME:d=["Restart","Menu","Resume"];break;case thirdButton.GAME_OVER:d=["Restart","Menu","Lose"];break;case thirdButton.NEXT:d=["Next","Menu","Win"];break;case thirdButton.END:d=["The End","End"]}this.game_state=a;this.nextLevel=c;this.menu=a.game.add.image(a.width/2,a.height/2,"pauseBkg");this.menu.anchor.setTo(0,0);this.menu.smoothed=!1;this.menu.width=a.world.width;this.menu.height=a.world.height;this.buttons=[];var e;for(b=
0;b<d.length;b++){var f=d[b];if("Lose"===f||"Win"===f||"End"===f){switch(f){case "Lose":e="You are dead";break;case "Win":e="Level Complete";break;case "End":e="Congratulations !"}c=a.game.add.text(a.game.camera.x+a.game.width/2,a.game.height/2+a.game.camera.y-100+70*b,e,{font:"Verdana",fontSize:"60px",fill:"#ffffff"});c.anchor.setTo(.5,0)}else c=a.game.add.button(a.game.camera.x+a.game.width/2,a.game.height/2+a.game.camera.y-100+70*b,"button",this.buttonClicked,this,0,1,2),c.name=f,c.anchor.setTo(.5,
.5),f=a.game.add.text(0,0,c.name,{font:"Verdana",fontSize:"32px",fill:"#ffffff"}),f.anchor.setTo(.5,.5),c.addChild(f),a.world.bringToTop(c),this.buttons[b]=c}d=!1;for(e=0;e<gameConstants.powerUps.length;e++)userGameData.money>=gameConstants.powerUps[e].cost&&(d=!0);d&&userGameData.powerUps.length<gameConstants.powerUps.length-userGameData.powerUpsDisabled.length&&(d=a.game.add.text(a.game.camera.x+a.game.width/2,a.game.height/2+a.game.camera.y-220,"You can buy a powerup !\nGo to the shop in the menu",
{font:"Verdana",fontSize:"25px",fill:"#ffffff",align:"center"}),d.anchor.setTo(.5,0),this.buttons.push(d));myGame.input.onDown.add(this.buttonClicked,this);a.game.paused=!0;a.game.input.enabled=!0};var thirdButton={NEXT:"Next Level",RESUME:"Resume",GAME_OVER:"Game Over",END:"End"};
Platformer.PauseMenu.prototype.buttonClicked=function(a){var b;for(b=0;b<this.buttons.length;b++){var c=this.buttons[b],d=(new Phaser.Rectangle).copyFrom(c);d.setTo(d.x-d.halfWidth,d.y-d.halfHeight,d.width,d.height);if(d.contains(a.x+a.game.camera.x,a.y+a.game.camera.y))switch(c.name){case "Restart":this.game_state.game.paused=!1;myGame.input.onDown.removeAll();this.game_state.restart_level();break;case "Menu":this.game_state.game.paused=!1;myGame.input.onDown.removeAll();myGame.state.start("BootState",
!0,!1,"menu");break;case "Resume":this.game_state.game.paused=!1;myGame.input.onDown.removeAll();this.menu.destroy();for(b=0;b<this.buttons.length;b++)this.buttons[b].destroy();break;case "Next":this.game_state.game.paused=!1;myGame.input.onDown.removeAll();myGame.state.start("BootState",!0,!1,this.nextLevel);break;case "The End":this.game_state.game.paused=!1,myGame.input.onDown.removeAll(),myGame.state.start("SettingsMenu",!0,!1,!0)}}};var Phaser=Phaser||{},Platformer=Platformer||{},userGameData=userGameData||{},gameConstants=gameConstants||{};Platformer.SettingsMenu=function(){Phaser.State.call(this)};Platformer.prototype=Object.create(Phaser.State.prototype);Platformer.prototype.constructor=Platformer.SettingsMenu;Platformer.SettingsMenu.prototype.init=function(a){this.ending=a};Platformer.SettingsMenu.prototype.preload=function(){};
Platformer.SettingsMenu.prototype.create=function(){var a=this.add.sprite(0,0,"background");a.width=this.game.width;a.height=this.game.height;a.smoothed=!1;this.menuContainer=this.add.group();this.ending?this.showCredits():this.createSettingsMenu(this.menuContainer)};Platformer.SettingsMenu.prototype.update=function(){this.endText&&-50>this.endText.world.y&&this.destroyCredits()};
Platformer.SettingsMenu.prototype.buttonPress=function(a){"Menu"===a.name?(saveProgress(),myGame.state.start("BootState",!0,!1,"menu")):"Credits"===a.name?this.showCredits():(a.getChildAt(1).setText("Press new key"),this.game.input.keyboard.onDownCallback=function(b){a.getChildAt(1).setText(keymapAscii[b.keyCode]);switch(a.name){case "Left":userGameData.leftKey=b.keyCode;break;case "Right":userGameData.rightKey=b.keyCode;break;case "Attack":userGameData.basicAttackKey=b.keyCode;break;case "Jump":userGameData.jumpKey=
b.keyCode;break;case "Fireball":userGameData.cast1Key=b.keyCode;break;case "Waterball":userGameData.cast2Key=b.keyCode}this.game.input.keyboard.onDownCallback=null})};Platformer.SettingsMenu.prototype.purchase=function(a,b){userGameData.money-=b;userGameData.powerUps.push(a);this.moneyTextSprite.setText(this.moneyText+userGameData.money)};
Platformer.SettingsMenu.prototype.showCredits=function(){this.menuContainer.removeChildren();var a=this.game.height/2,b=this.make.sprite(this.game.width/2,a,"logo");b.scale.setTo(.6,.6);b.anchor.setTo(.5,.5);this.menuContainer.addChild(b);this.physics.arcade.enable(b);b.body.allowGravity=!1;var c={font:"Verdana",fontSize:"32px",fill:"#ffffff",align:"center"},a=this.game.make.text(0,a+100,"---  Design and programming ---\nFabio Siliberto\nfor:\nTDDD23 course - LiU",c);a.anchor.setTo(.5,.5);b.addChild(a);
a=a.bottom+100;a=this.game.make.text(0,a,"--- Graphics sources ---\nflamingtext.com\nUniversal-LPC-spritesheet by jrconway3\nrosprites.blogspot.com\ngamegraphycs.do.am\nrpgmakervxace.net",c);a.anchor.setTo(.5,0);b.addChild(a);a=a.bottom+100;a=this.game.make.text(0,a,"--- Special thanks ---\nEmanuela for the name and testing\nMarco, Antonio, Sergio,\nFederica, Vezio, Dorian,\nViktor, Linda\nfor testing",c);a.anchor.setTo(.5,0);b.addChild(a);a=a.bottom+100;this.endText=this.game.make.text(0,a,"--- THANK YOU ! ---",
c);this.endText.anchor.setTo(.5,0);b.addChild(this.endText);b.body.velocity.y=-50;this.input.onDown.add(this.destroyCredits,this)};Platformer.SettingsMenu.prototype.destroyCredits=function(a){this.menuContainer.removeChildren();this.createSettingsMenu(this.menuContainer);this.endText=null;this.input.onDown.removeAll();this.ending&&myGame.state.start("LoadingState",!0,!1,"menu")};
Platformer.SettingsMenu.prototype.createSettingsMenu=function(a){var b=this.add.image(150,60,"logo");b.scale.setTo(.3,.3);b.anchor.setTo(.5,.5);a.addChild(b);b=this.game.add.text(this.game.width/2,125,"Settings",{font:"Verdana",fontSize:"32px",fill:"#ffffff"});b.anchor.setTo(.5,.5);a.addChild(b);var c,d,e,f,g,h;c=this.game.add.button(this.game.width/2+275,60,"button",this.buttonPress,this,0,1,2);c.anchor.setTo(.5,.5);c.scale.setTo(.8,.8);c.name="Menu";d=this.game.make.text(0,0,c.name,{font:"Verdana",
fontSize:"32px",fill:"#ffffff"});d.anchor.setTo(.5,.5);c.addChild(d);a.addChild(c);e="Left Right Jump Attack Fireball Snowball".split(" ");h=[userGameData.leftKey,userGameData.rightKey,userGameData.jumpKey,userGameData.basicAttackKey,userGameData.cast1Key,userGameData.cast2Key];for(b=g=f=0;b<e.length;b++)c=this.game.add.button(220+300*f,200+50*g,"button",this.buttonPress,this,0,1,2),c.scale.setTo(.7,.7),c.name=e[b],c.anchor.setTo(.5,.5),d=this.game.make.text(0,0,e[b],{font:"Verdana",fontSize:"28px",
fill:"#ffffff",align:"top"}),d.anchor.setTo(.5,.5),c.addChild(d),d=this.game.make.text(100,0,keymapAscii[h[b]],{font:"Verdana",fontSize:"28px",fill:"#ffffff",align:"top"}),d.anchor.setTo(0,.5),c.addChild(d),a.addChild(c),0===(b+1)%2?(g+=1,f=0):f+=1;c=this.game.add.button(this.game.width/2,50*g+300,"button",this.buttonPress,this,0,1,2);c.scale.setTo(.7,.7);c.name="Credits";c.anchor.setTo(.5,.5);d=this.game.make.text(0,0,c.name,{font:"Verdana",fontSize:"28px",fill:"#ffffff",align:"top"});d.anchor.setTo(.5,
.5);c.addChild(d);a.addChild(c)};Phaser=Phaser||{};Platformer=Platformer||{};userGameData=userGameData||{};gameConstants=gameConstants||{};Platformer.ShopMenu=function(){Phaser.State.call(this)};Platformer.prototype=Object.create(Phaser.State.prototype);Platformer.prototype.constructor=Platformer.ShopMenu;Platformer.ShopMenu.prototype.init=function(){};Platformer.ShopMenu.prototype.preload=function(){};
Platformer.ShopMenu.prototype.create=function(){var a=this.add.sprite(0,0,"background");a.width=this.game.width;a.height=this.game.height;a.smoothed=!1;this.logo=this.add.image(150,60,"logo");this.logo.scale.setTo(.3,.3);this.logo.anchor.setTo(.5,.5);this.game.add.text(this.game.width/2,125,"Shop",{font:"Verdana",fontSize:"32px",fill:"#ffffff"}).anchor.setTo(.5,.5);var b,c,d,e,f;c=this.game.add.button(this.game.width/2+275,60,"button",this.buttonPress,this,0,1,2);c.anchor.setTo(.5,.5);c.scale.setTo(.8,
.8);c.name={name:"Menu"};d=this.game.make.text(0,0,c.name.name,{font:"Verdana",fontSize:"32px",fill:"#ffffff"});d.anchor.setTo(.5,.5);c.addChild(d);for(a=0;a<gameConstants.powerUps.length;a++)d=gameConstants.powerUps[a].text,b=gameConstants.powerUps[a].name,e=gameConstants.powerUps[a].cost,contains(userGameData.powerUpsDisabled,b)?(c=this.game.add.sprite(175+a/2*300,this.game.height/2+75,"disabledShopButton"),c.anchor.setTo(.5,.5)):(contains(userGameData.powerUps,b)?(c=this.game.add.sprite(175+a/
2*300,this.game.height/2+75,"shopButton"),f="Obtained",c.frame=2):(c=this.game.add.button(175+a/2*300,this.game.height/2+75,"shopButton",this.buttonPress,this,0,1,2),f="Cost:\n"+e),c.name={name:b,cost:e},c.anchor.setTo(.5,.5),d=this.game.make.text(0,-65,d,{font:"Verdana",fontSize:"23px",fill:"#ffffff",align:"center"}),d.anchor.setTo(.5,.5),e=this.game.make.image(0,-15,b),e.anchor.setTo(.5,.5),"waterball"===b&&e.scale.setTo(.7,.7),b=this.game.make.text(0,65,f,{font:"Verdana",fontSize:"20px",fill:"#ffffff",
align:"center"}),b.anchor.setTo(.5,.5),c.addChild(d),c.addChild(e),c.addChild(b));this.moneyText="Your coins: ";this.moneyTextSprite=this.game.add.text(this.game.width/2,225,this.moneyText+userGameData.money,{font:"Verdana",fontSize:"27px",fill:"#ffffff"});this.moneyTextSprite.anchor.setTo(.5,.5)};
Platformer.ShopMenu.prototype.buttonPress=function(a){switch(a.name.name){case "Menu":saveProgress();myGame.state.start("BootState",!0,!1,"menu");break;case "hearth":userGameData.money>=a.name.cost&&(this.purchase(a.name.name,a.name.cost),a.input.enabled=!1,a.freezeFrames=!0,a.frame=2,a.children[2].setText("Obtained"),userGameData.maxHealth+=1);break;case "mana":userGameData.money>=a.name.cost&&(this.purchase(a.name.name,a.name.cost),a.input.enabled=!1,a.freezeFrames=!0,a.frame=2,a.children[2].setText("Obtained"),
userGameData.maxMana+=1);break;case "fireball":userGameData.money>=a.name.cost&&(this.purchase(a.name.name,a.name.cost),a.input.enabled=!1,a.freezeFrames=!0,a.frame=2,a.children[2].setText("Obtained"),userGameData.rangeFireball+=1E3);break;case "waterball":userGameData.money>=a.name.cost&&(this.purchase(a.name.name,a.name.cost),a.input.enabled=!1,a.freezeFrames=!0,a.frame=2,a.children[2].setText("Obtained"),userGameData.rangeWaterball+=1E3)}};
Platformer.ShopMenu.prototype.purchase=function(a,b){userGameData.money-=b;userGameData.powerUps.push(a);this.moneyTextSprite.setText(this.moneyText+userGameData.money)};Phaser=Phaser||{};Platformer=Platformer||{};userGameData=userGameData||{};Platformer.TiledState=function(){Phaser.State.call(this)};Platformer.TiledState.prototype=Object.create(Phaser.State.prototype);Platformer.TiledState.prototype.constructor=Platformer.TiledState;
Platformer.TiledState.prototype.init=function(a){this.level_data=a;this.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;this.scale.pageAlignHorizontally=!0;this.scale.pageAlignVertically=!0;this.physics.startSystem(Phaser.Physics.ARCADE);this.physics.arcade.gravity.y=1E3;this.map=this.add.tilemap(a.map.key);var b=0;this.map.tilesets.forEach(function(a){this.map.addTilesetImage(a.name,this.level_data.map.tilesets[b]);b+=1},this)};
Platformer.TiledState.prototype.create=function(){var a,b;this.stage.backgroundColor=this.level_data.properties.bkgColor||"#80B0DA";this.layers={};var c,d,e;c=0;for(d=this.map.images.length;c<d;c++)e=this.map.images[c],e=this.add.sprite(e.x,e.y,e.name),e.smoothed=!1;this.map.layers.forEach(function(a){this.layers[a.name]=this.map.createLayer(a.name);a.properties.collision&&(b=[],a.data.forEach(function(a){a.forEach(function(a){0<a.index&&-1===b.indexOf(a.index)&&b.push(a.index)},this)},this),this.map.setCollision(b,
!0,a.name));a.properties.traps&&(b=[],a.data.forEach(function(a){a.forEach(function(a){0<a.index&&-1===b.indexOf(a.index)&&b.push(a.index)},this)},this),this.map.setTileIndexCallback(b,this.hitPlayer,this,a.name))},this);this.layers[this.map.layer.name].resizeWorld();e&&(e.width=this.world.width,e.height=this.world.height);this.groups={};this.level_data.groups.forEach(function(a){this.groups[a]=this.add.group()},this);this.basicObjects={};for(a in this.map.objects)this.map.objects.hasOwnProperty(a)&&
this.map.objects[a].forEach(this.create_object,this);this.world.bringToTop(this.groups.enemies);this.world.bringToTop(this.groups.items);this.world.bringToTop(this.groups.players);a=this.add.button(this.game.width/2,20,"button",this.loadPauseMenu,this,0,1,2);a.anchor.setTo(.5,.5);a.scale.setTo(.5,.5);c=this.game.make.text(0,0,"Pause",{font:"Verdana",fontSize:"34px",fill:"#ffffff"});c.anchor.setTo(.5,.5);a.addChild(c);a.fixedToCamera=!0;this.money=userGameData.money;this.moneyText="Coins: ";this.moneyTextSprite=
this.game.add.text(this.game.width-5,5,this.moneyText+this.money,{font:"Verdana",fontSize:"27px",fill:"#000000"});this.moneyTextSprite.anchor.setTo(1,0);this.moneyTextSprite.fixedToCamera=!0;this.camera.follow(this.basicObjects.Byron)};Platformer.TiledState.prototype.hitPlayer=function(){this.basicObjects.Byron.damage(1)};Platformer.TiledState.prototype.addCoins=function(a){this.money+=a;this.moneyTextSprite.setText(this.moneyText+this.money)};
Platformer.TiledState.prototype.create_object=function(a){var b,c;b={x:a.x+this.map.tileHeight/2,y:a.y-this.map.tileHeight/2};switch(a.type){case "Byron":c=new Platformer.Byron(this,b,a.properties);break;case "ground_enemy":c=new Platformer.Enemy(this,b,a.properties);break;case "flyingEnemy":c=new Platformer.FlyingEnemy(this,b,a.properties);break;case "flyingEnemyCloseRange":c=new Platformer.FlyingEnemyCloseRange(this,b,a.properties);break;case "goal":c=new Platformer.Goal(this,b,a.properties);break;
case "item":c=new Platformer.Item(this,b,a.properties);break;case "sign":c=new Platformer.Sign(this,b,a.properties);break;case "blob":c=new Platformer.Blob(this,b,a.properties);break;case "archer":c=new Platformer.Archer(this,b,a.properties);break;case "fighter":c=new Platformer.Fighter(this,b,a.properties);break;case "skeleton":c=new Platformer.Skeleton(this,b,a.properties);break;case "wakwak":c=new Platformer.Wakwak(this,b,a.properties);break;case "clock":c=new Platformer.Clock(this,b,a.properties);
break;case "helper":c=new Platformer.HelperGuy(this,b,a.properties)}this.basicObjects[a.name]=c};Platformer.TiledState.prototype.restart_level=function(){myGame.state.restart(!0,!1,this.level_data)};Platformer.TiledState.prototype.nextLevel=function(a){new Platformer.PauseMenu(this,thirdButton.NEXT,a)};Platformer.TiledState.prototype.loadPauseMenu=function(){new Platformer.PauseMenu(this,thirdButton.RESUME)};Platformer.TiledState.prototype.playerDead=function(){new Platformer.PauseMenu(this,thirdButton.GAME_OVER)};
Platformer.TiledState.prototype.spawnItem=function(a,b){new Platformer.Item(this,b,{texture:a,group:"items"})};Platformer.TiledState.prototype.render=function(){};Phaser=Phaser||{};Platformer=Platformer||{};Platformer.BasicObject=function(a,b,c){Phaser.Sprite.call(this,a.game,b.x,b.y,c.texture);this.game_state=a;this.objectGame=a.game;c.group&&this.game_state.groups[c.group].add(this);this._super=Platformer.BasicObject.prototype;this._superSprite=Phaser.Sprite.prototype};Platformer.BasicObject.prototype=Object.create(Phaser.Sprite.prototype);Platformer.BasicObject.prototype.constructor=Platformer.BasicObject;Platformer=Platformer||{};Phaser=Phaser||{};
Platformer.Enemy=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.properties=c;this.altitude=c.altitude||0;this.objectGame.physics.arcade.enable(this);this.walking_speed=70;this.body.velocity.x=this.walking_speed*c.direction;c.bodySizeW&&this.body.setSize(c.bodySizeW,c.bodySizeH);this.maxHealth=c.health/1;this.heal(this.maxHealth);a=this.game_state.game.make.sprite(0,-this.body.height-10,"healthBarL");b=this.maxHealth/2;var d;a.anchor.setTo(b-0,0);a.setScaleMinMax(1,1);this.addChild(a);
for(d=1;d<this.maxHealth-1;d++)a=this.game_state.game.make.sprite(0,-this.body.height-10,"healthBarC"),a.anchor.setTo(b-d,0),a.setScaleMinMax(1,1),this.addChild(a);a=this.game_state.game.make.sprite(0,-this.body.height-10,"healthBarR");a.anchor.setTo(b-d,0);a.setScaleMinMax(1,1);this.addChild(a);this.previous_x=this.x;this.maxDistance=+c.maxDistance;this.attacking=!1;this.preventAttack=c.attackRate/1||2300;this.nextAttack=0};Platformer.Enemy.prototype=Object.create(Platformer.BasicObject.prototype);
Platformer.Enemy.prototype.constructor=Platformer.Enemy;
Platformer.Enemy.prototype.update=function(a){if(this.alive)if(this.game_state.game.physics.arcade.collide(this,this.game_state.layers.collision),this.objectGame.physics.arcade.overlap(this,this.game_state.groups.players,this.damagePlayer,null,this),a)this.body.velocity.x=0;else{if(!this.has_tile_to_walk()||this.body.blocked.left||this.body.blocked.right)this.attacking?this.body.velocity.x=0:this.switchDirection();this.maxDistance&&Math.abs(this.x-this.previous_x)>=this.maxDistance&&this.switchDirection()}};
Platformer.Enemy.prototype.switchDirection=function(){this.properties.direction*=-1;this.previous_x=this.x;this.body.velocity.x=this.properties.direction*this.walking_speed;0<this.body.velocity.x?this.animations.play("moveRight"):this.animations.play("moveLeft")};Platformer.Enemy.prototype.damagePlayer=function(a,b){b.damage(1)};
Platformer.Enemy.prototype.kill=function(){this._superSprite.kill.call(this);var a=this.objectGame.rnd,b=this.y-this.body.height;a.frac()<userGameData.manaPotProb&&this.game_state.spawnItem("manaPot",{x:this.x,y:b});a.frac()<userGameData.healthPotProb&&this.game_state.spawnItem("healthPot",{x:this.x,y:b});var c;for(c=0;c<gameConstants.coinSpawnNumber;c++){var d=a.weightedPick(["Copper","Silver","Gold"]);a.frac()<gameConstants.coinSpawnProb&&this.game_state.spawnItem(d+"Coin",{x:this.x,y:b})}};
Platformer.Enemy.prototype.has_tile_to_walk=function(){var a,b;a=new Phaser.Point(this.x+this.properties.direction*this.body.width/2,this.y+24*this.altitude+12+1);b=this.game_state.map;return null!==b.getTileWorldXY(a.x,a.y,b.tileWidth,b.tileHeight,"collision")};Platformer.Enemy.prototype.damage=function(a){0!==a&&(a=this._superSprite.damage.call(this,a).health,0<a?this.removeChildAt(a):this.destroy())};
Platformer.Enemy.prototype.detect_player=function(a){var b=this.objectGame.time.now;if(b<this.nextAttack)return!1;var c=this.game_state.basicObjects.Byron.x,d=this.x-c,c=Math.sqrt(Math.pow(this.x-c,2)+Math.pow(this.y-this.game_state.basicObjects.Byron.y,2))<=this.attackDistance;0<d*this.properties.direction&&c&&a&&this.switchDirection();if(c=c&&(0>d*this.properties.direction||a))this.nextAttack=b+this.preventAttack;return c};
Platformer.Enemy.prototype.blink=function(){this.objectGame.time.now>this.dyingTime?(this.alpha=1,this._superSprite.kill.call(this),this.objectGame.time.events.remove(this.blinking)):this.alpha=1===this.alpha?.3:1};Platformer=Platformer||{};userGameData=userGameData||{};Platformer.Goal=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.nextLevel=c.next_level;this.type=c.texture;this.game_state.game.physics.arcade.enable(this);this.body.allowGravity=!1;this.anchor.setTo(.5,0)};Platformer.Goal.prototype=Object.create(Platformer.BasicObject.prototype);Platformer.Goal.prototype.constructor=Platformer.Goal;
Platformer.Goal.prototype.update=function(){this.game_state.game.physics.arcade.collide(this,this.game_state.layers.collision);this.game_state.game.physics.arcade.overlap(this,this.game_state.groups.players,this.goalReached,null,this)};
Platformer.Goal.prototype.goalReached=function(a,b){userGameData.money=this.game_state.money;userGameData.levelsUnlocked.push(this.nextLevel);saveProgress();"end"===this.nextLevel?new Platformer.PauseMenu(this.game_state,thirdButton.END):a.game_state.nextLevel("Level "+this.nextLevel)};Platformer=Platformer||{};Platformer.Item=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.game_state.game.physics.arcade.enable(this);this.type=c.texture;this.anchor.setTo(.5,0);c["static"]?this.body.allowGravity=!1:(this.body.bounce.y=.6,this.body.collideWorldBounds=!0,a=this.objectGame.rnd,this.body.velocity.x=150*a.realInRange(.4,1)*a.pick([-1,1]),this.body.velocity.y=-300*a.realInRange(.3,.8))};Platformer.Item.prototype=Object.create(Platformer.BasicObject.prototype);
Platformer.Item.prototype.constructor=Platformer.Item;Platformer.Item.prototype.update=function(){this.game_state.game.physics.arcade.collide(this,this.game_state.layers.collision);1<this.body.velocity.x?--this.body.velocity.x:this.body.velocity.x=-1>this.body.velocity.x?this.body.velocity.x+1:0};Platformer=Platformer||{};
Platformer.Sign=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.game_state.game.physics.arcade.enable(this);this.body.bounce.y=0;this.body.setSize(1.5*this.body.width,this.body.height,0,0);this.anchor.setTo(.5,.5);switch(c.text){case "1":a="Try '"+keymapAscii[userGameData.leftKey]+"'\nand '"+keymapAscii[userGameData.rightKey]+"'";break;case "2":a="'"+keymapAscii[userGameData.jumpKey]+"'\nto jump";break;case "3":a="Try '"+keymapAscii[userGameData.jumpKey]+"'\nin air";break;case "4":a=
"'"+keymapAscii[userGameData.basicAttackKey]+"'\nto attack";break;default:a=c.text.toString().replace("\\n","\n")}a=this.game.make.text(0,5,a,{fontSize:"14px",stroke:"#000000",align:"center"});a.anchor.setTo(.5,1);this.addChild(a);this.renderable=!1};Platformer.Sign.prototype=Object.create(Platformer.BasicObject.prototype);Platformer.Sign.prototype.constructor=Platformer.Sign;
Platformer.Sign.prototype.update=function(){this.game_state.game.physics.arcade.collide(this,this.game_state.layers.collision);this.renderable||this.game_state.game.physics.arcade.overlap(this,this.game_state.basicObjects.Byron,this.collided,null)};Platformer.Sign.prototype.collided=function(a){a===a.game_state.basicObjects.Tutorial4&&(userGameData.healthPotProb=gameConstants.healthPotProb);a.renderable=!0};Platformer=Platformer||{};
Platformer.Archer=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.anchor.setTo(.5,.75);this.animations.add("moveLeft",_.range(117,126),20,!0);this.animations.add("moveRight",_.range(143,152),20,!0);a=this.animations.add("shootLeft",_.range(221,232),25,!1);a.onComplete.add(function(){this.attacking=!1;this.animations.play("moveLeft")},this);a=this.animations.add("shootRight",_.range(247,258),25,!1);a.onComplete.add(function(){this.attacking=
!1;this.animations.play("moveRight")},this);this.frame=0>this.properties.direction?221:247;this.arrows=this.objectGame.add.group();for(a=0;5>a;a++)this.arrows.add(new Platformer.EnemyProjectile(this.game_state,{x:0,y:0},{texture:"arrow",speed:300,maxTime:this.attackDistance,type:"straight"}))};Platformer.Archer.prototype=Object.create(Platformer.Enemy.prototype);Platformer.Archer.prototype.constructor=Platformer.Archer;
Platformer.Archer.prototype.update=function(){if(this.detect_player(!1)){var a=0<this.properties.direction?"shootRight":"shootLeft";setTimeout(function(a){a.alive&&a.arrows.getFirstDead().fire(a.x,a.y-10,a.properties.direction)},360,this);this.animations.play(a);this.attacking=!0}this._super.update.call(this,!0);this.attacking?this.body.velocity.x=0:this.frame=0>this.properties.direction?221:247};Platformer=Platformer||{};Phaser=Phaser||{};
Platformer.Blob=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;"blob"===c.texture?(this.anchor.setTo(.5,1),this.animations.add("moveRight",[0,1,2,3],10,!0),this.animations.add("moveLeft",[4,5,6,7],10,!0)):"slime"===c.texture?(this.anchor.setTo(.5,.9),this.scale.setTo(1.5,1.5),this.animations.add("moveLeft",Phaser.Animation.generateFrameNames("slime",2,5,"",0),10,!0),this.animations.add("moveRight",Phaser.Animation.generateFrameNames("slimeR",
2,5,"",0),10,!0)):"crocodile"===c.texture&&(this.anchor.setTo(.5,.75),this.body.setSize(this.body.width,this.body.height-2,0,-2),this.animations.add("moveLeft",[0,1,2,3],10,!0),this.animations.add("moveRight",[4,5,6,7],10,!0));this.animations.play("moveLeft");this.switched=!0;this.go=!1};Platformer.Blob.prototype=Object.create(Platformer.Enemy.prototype);Platformer.Blob.prototype.constructor=Platformer.Blob;
Platformer.Blob.prototype.update=function(){this._super.update.call(this);"crocodile"===this.properties.texture&&this.detect_player(!0)&&(this.attacking=!0,setTimeout(function(a){a.go=!0},300,this));!0===this.attacking&&this.switched&&(this.go?(this.body.velocity.x=250*this.properties.direction,this.go=this.attacking=this.switched=!1):(this.body.velocity.x=0,this.frame=0>this.properties.direction?0:4))};
Platformer.Blob.prototype.switchDirection=function(){this._super.switchDirection.call(this);this.switched=!0};Platformer=Platformer||{};Phaser=Phaser||{};
Platformer.Clock=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.anchor.setTo(.5,.8);this.scale.setTo(.8,.8);this.body.setSize(this.properties.bodySizeW,this.properties.bodySizeH,0,0);this.animations.add("moveLeft",Phaser.Animation.generateFrameNames("left",1,16,"",0),15,!0);this.animations.add("moveRight",Phaser.Animation.generateFrameNames("right",1,16,"",0),15,!0);a=this.animations.add("attackLeft",Phaser.Animation.generateFrameNames("left",
17,32,"",0),20,!1);a.onStart.add(this.resizeAttackBody,this,0,"left");a.onComplete.add(this.resizeOriginalBody,this);a=this.animations.add("attackRight",Phaser.Animation.generateFrameNames("right",17,32,"",0),20,!1);a.onStart.add(this.resizeAttackBody,this,0,"right");a.onComplete.add(this.resizeOriginalBody,this);this.animations.play("moveLeft")};Platformer.Clock.prototype=Object.create(Platformer.Enemy.prototype);Platformer.Clock.prototype.constructor=Platformer.Clock;
Platformer.Clock.prototype.resizeOriginalBody=function(){this.attacking=!1;this.anchor.setTo(.5,.8);this.body.setSize(this.properties.bodySizeW,this.properties.bodySizeH,0,0);this.animations.play(0>this.properties.direction?"moveLeft":"moveRight")};
Platformer.Clock.prototype.resizeAttackBody=function(a,b,c){this.attacking=!0;this.anchor.setTo(0<this.properties.direction?.2:.8,.8);setTimeout(function(a,b){a.alive&&a.body.setSize(a.properties.bodySizeW/1+155,a.properties.bodySizeH,b*a.properties.bodySizeW/2,0)},400,this,"left"===c?-1:1)};
Platformer.Clock.prototype.update=function(){this._super.update.call(this);this.detect_player(!1)&&(setTimeout(function(a){a.alive&&a.animations.play(0>a.properties.direction?"attackLeft":"attackRight")},400,this),this.attacking=!0);this._super.update.call(this);this.body.velocity.x=this.attacking?0:this.properties.direction*this.walking_speed};Platformer=Platformer||{};Platformer.EnemyProjectile=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.objectGame.physics.arcade.enable(this);this.speed=c.speed;this.maxTime=3.5*c.maxTime;this.killTime=0;this.txt=c.type;this.properties=c;this.anchor.setTo(.5,.5);this.body.allowGravity=!1;"largeBullet"===c.texture&&(this.anchor.setTo(.5,.3),this.scale.setTo(.5,.5),this.body.setSize(15,35),this.maxTime*=1.5);this.outOfBoundsKill=this.checkWorldBounds=!0;this.kill()};
Platformer.EnemyProjectile.prototype=Object.create(Platformer.BasicObject.prototype);Platformer.EnemyProjectile.prototype.constructor=Platformer.EnemyProjectile;Platformer.EnemyProjectile.prototype.update=function(){this.alive&&(this.objectGame.physics.arcade.collide(this,this.game_state.layers.collision,this.collisionDetected),this.objectGame.physics.arcade.overlap(this,this.game_state.groups.players,this.hitPlayer,null,this),this.objectGame.time.now>this.killTime&&this.kill())};
Platformer.EnemyProjectile.prototype.hitPlayer=function(a,b){this.kill();b.damage(1)};Platformer.EnemyProjectile.prototype.collisionDetected=function(a,b){a.kill()};
Platformer.EnemyProjectile.prototype.fire=function(a,b,c,d,e){this.killTime=this.objectGame.time.now+this.maxTime;this.direction=c;this.reset(a-c*this.width/3,b);var f=0;switch(this.txt){case "straight":this.frame=0<c?1:0;break;case "directional":f=180*Math.atan2(b-e,a-d)/Math.PI,"largeBullet"===this.properties.texture?this.frame=0<c?1:0:this.angle=f,c=-1,this.body.velocity.y=c*this.speed*Math.sin(f*Math.PI/180)}this.body.velocity.x=c*this.speed*Math.cos(f*Math.PI/180)};Platformer=Platformer||{};
Platformer.Fighter=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.anchor.setTo(.5,.75);this.animations.add("moveLeft",_.range(117,126),20,!0);this.animations.add("moveRight",_.range(143,152),20,!0);a=this.animations.add("attackRight",_.range(195,201),15,!1);this.animations.add("attackLeft",_.range(169,175),15,!1);this.weapon=this.objectGame.make.sprite(0,0,"orcWeapon");this.weapon.anchor.setTo(.5,.55);this.attackRange=
30;this.weapon.name="weapon";a=this.weapon.animations.add("attackLeft",_.range(7,12),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"left");a.onComplete.add(this.resizeOriginalBody,this);a=this.weapon.animations.add("attackRight",_.range(19,24),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"right");a.onComplete.add(this.resizeOriginalBody,this);this.weapon.visible=!1;this.addChild(this.weapon);this.objectGame.physics.arcade.enable(this.weapon);this.weapon.body.allowGravity=!1;this.weapon.body.setSize(0,
0,0,0);this.wait=!1};Platformer.Fighter.prototype=Object.create(Platformer.Enemy.prototype);Platformer.Fighter.prototype.constructor=Platformer.Fighter;Platformer.Fighter.prototype.resizeOriginalBody=function(){this.attacking=this.weapon.visible=!1;this.weapon.body.setSize(0,0,0,0);this.animations.play(0>this.properties.direction?"moveLeft":"moveRight")};
Platformer.Fighter.prototype.resizeAttackBody=function(a,b,c){this.attacking=!0;this.wait=!1;this.weapon.visible=!0;setTimeout(function(a,b){a.weapon.body.setSize(a.attackRange,a.height-40,b*a.width/2,-6)},1/15*1E3,this,"left"===c?-1:1)};
Platformer.Fighter.prototype.update=function(){this.weapon.visible&&this.objectGame.physics.arcade.overlap(this.weapon,this.game_state.groups.players,this.playerHit,null,this);this.detect_player(!1)&&(setTimeout(function(a){setTimeout(function(a){if(a.alive){var c=0>a.properties.direction?"attackLeft":"attackRight";a.animations.play(c);a.weapon.animations.play(c)}},400,a);a.wait=!1},300,this),this.attacking=this.wait=!0);this._super.update.call(this);this.attacking?this.wait?(this.body.velocity.x=
!0,this.frame=0>this.properties.direction?117:143):0!==this.body.velocity.x&&(this.body.velocity.x=150*this.properties.direction):this.body.velocity.x=this.properties.direction*this.walking_speed};Platformer.Fighter.prototype.playerHit=function(a,b){b.damage(1)};Platformer=Platformer||{};
Platformer.FlyingEnemy=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.body.allowGravity=!1;this.anchor.setTo(.5,.5);this.animations.add("moveLeft",[0,1,2],12,!0);this.animations.add("moveRight",[3,4,5],12,!0);this.animations.play("moveLeft");"libellula"===c.texture&&this.scale.setTo(.9,.9);this.bullets=this.objectGame.add.group();for(a=0;5>a;a++)this.bullets.add(new Platformer.EnemyProjectile(this.game_state,{x:0,
y:0},{texture:"bullet",speed:300,maxTime:this.attackDistance,type:"directional"}))};Platformer.FlyingEnemy.prototype=Object.create(Platformer.Enemy.prototype);Platformer.FlyingEnemy.prototype.constructor=Platformer.FlyingEnemy;
Platformer.FlyingEnemy.prototype.update=function(){if(this.detect_player(!1)){var a=0<this.properties.direction?4:1;setTimeout(function(a,c,d){a.alive&&a.bullets.getFirstDead().fire(a.x,a.y-10,a.properties.direction,c,d);a.attacking=!1},200,this,this.game_state.basicObjects.Byron.x,this.game_state.basicObjects.Byron.y);this.properties.attacksNum&&setTimeout(function(a){var c=a.game_state.basicObjects.Byron.x,d=a.game_state.basicObjects.Byron.y;a.alive&&a.bullets.getFirstDead().fire(a.x,a.y-10,a.properties.direction,
c,d)},500,this);this.animations.stop();this.animations.frame=a;this.attacking=!0}this._super.update.call(this,this.attacking);this.attacking?this.body.velocity.x=0:(this.body.velocity.x=this.properties.direction*this.walking_speed,this.animations.play(0>this.properties.direction?"moveLeft":"moveRight"))};Platformer=Platformer||{};
Platformer.FlyingEnemyCloseRange=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.body.allowGravity=!1;this.anchor.setTo(.5,.5);this.scale.setTo(.9,.9);this.animations.add("moveLeft",Phaser.Animation.generateFrameNames("left",1,16,"",0),12,!0);this.animations.add("moveRight",Phaser.Animation.generateFrameNames("right",1,16,"",0),12,!0);this.animations.play("moveLeft");a=this.animations.add("attackRight",Phaser.Animation.generateFrameNames("right",
17,24,"",0),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"right");a.onComplete.add(this.resizeOriginalBody,this);a=this.animations.add("attackLeft",Phaser.Animation.generateFrameNames("left",17,24,"",0),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"left");a.onComplete.add(this.resizeOriginalBody,this);this.prevPosition={};this.goingBack=!1;this.yTarget=this.xTarget=this.prevBodyY=this.prevY=this.prevX=0;this.targetAcquired=!1};Platformer.FlyingEnemyCloseRange.prototype=Object.create(Platformer.Enemy.prototype);
Platformer.FlyingEnemyCloseRange.prototype.constructor=Platformer.FlyingEnemyCloseRange;Platformer.FlyingEnemyCloseRange.prototype.resizeOriginalBody=function(){this.targetAcquired=this.attacking=!1;this.body.setSize(this.properties.bodySizeW,this.properties.bodySizeH,0,0);var a=0>this.properties.direction?"moveLeft":"moveRight";this.goingBack=!0;this.animations.play(a)};
Platformer.FlyingEnemyCloseRange.prototype.resizeAttackBody=function(a,b,c){this.targetAcquired=this.attacking=!0;this.body.setSize(this.properties.bodySizeW/1+10,this.properties.bodySizeH,("left"===c?-1:1)*this.properties.bodySizeW/2,0)};
Platformer.FlyingEnemyCloseRange.prototype.update=function(){if(this.goingBack){this.nextAttack=this.objectGame.time.now+this.preventAttack+200;this.objectGame.physics.arcade.moveToXY(this,this.prevX,this.prevY,200);var a=this.prevX-this.x,b=this.prevY-this.y;-2<a==2>a&&-2<b==2>b&&(this.goingBack=!1,this.body.velocity.y=0,this.body.y=this.prevBodyY)}else{if(this.detect_player(!1)&&!this.targetAcquired){var c=0>this.properties.direction?"attackLeft":"attackRight";this.prevX=this.x;this.prevY=this.y;
this.prevBodyY=this.body.y;this.xTarget=this.game_state.basicObjects.Byron.x;this.yTarget=this.game_state.basicObjects.Byron.y;setTimeout(function(a,b,f){a.animations.play(c)},300,this,c);this.animations.stop();this.attacking=!0}this._super.update.call(this,this.attacking);!this.targetAcquired&&this.attacking?(this.animations.stop(),this.body.velocity.x=0):this.targetAcquired?this.game_state.game.physics.arcade.moveToXY(this,this.xTarget,this.yTarget,200):(this.body.velocity.x=this.properties.direction*
this.walking_speed,this.animations.play(0>this.properties.direction?"moveLeft":"moveRight"))}};Platformer=Platformer||{};
Platformer.Skeleton=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.anchor.setTo(.5,.75);this.animations.add("moveLeft",_.range(117,126),20,!0);this.animations.add("moveRight",_.range(143,152),20,!0);a=this.animations.add("attackRight",_.range(92,98),15,!1);this.animations.add("attackLeft",_.range(66,72),15,!1);this.weapon=this.objectGame.make.sprite(0,0,"skeletonWeapon");this.weapon.anchor.setTo(.45,.58);this.attackRange=
50;this.weapon.name="weapon";a=this.weapon.animations.add("attackLeft",_.range(9,14),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"left");a.onComplete.add(this.resizeOriginalBody,this);a=this.weapon.animations.add("attackRight",_.range(25,30),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"right");a.onComplete.add(this.resizeOriginalBody,this);this.weapon.visible=!1;this.addChild(this.weapon);this.objectGame.physics.arcade.enable(this.weapon);this.weapon.body.allowGravity=!1;this.weapon.body.setSize(0,
0,0,0);this.wait=!1};Platformer.Skeleton.prototype=Object.create(Platformer.Enemy.prototype);Platformer.Skeleton.prototype.constructor=Platformer.Skeleton;Platformer.Skeleton.prototype.resizeOriginalBody=function(){this.attacking=this.weapon.visible=!1;this.weapon.body.setSize(0,0,0,0);this.animations.play(0>this.properties.direction?"moveLeft":"moveRight")};
Platformer.Skeleton.prototype.resizeAttackBody=function(a,b,c){this.attacking=!0;this.weapon.visible=!0;setTimeout(function(a,b){a.weapon.body.setSize(a.attackRange,a.height-40,b*a.width/2,-6)},1/15*1E3,this,"left"===c?-1:1)};
Platformer.Skeleton.prototype.update=function(){this.weapon.visible&&this.objectGame.physics.arcade.overlap(this.weapon,this.game_state.groups.players,this.playerHit,null,this);this._super.update.call(this);this.detect_player(!1)&&(setTimeout(function(a){setTimeout(function(a){if(a.alive){var c=0>a.properties.direction?"attackLeft":"attackRight";a.animations.play(c);a.weapon.animations.play(c)}},300,a);a.wait=!1},300,this),this.attacking=this.wait=!0);this.attacking?this.wait?(this.body.velocity.x=
!0,this.frame=0>this.properties.direction?117:143):this.has_tile_to_walk()&&(this.body.velocity.x=200*this.properties.direction):this.body.velocity.x=this.properties.direction*this.walking_speed};Platformer.Skeleton.prototype.playerHit=function(a,b){b.damage(1)};Platformer=Platformer||{};
Platformer.Wakwak=function(a,b,c){Platformer.Enemy.call(this,a,b,c);this._super=Platformer.Enemy.prototype;this.attackDistance=c.attackDistance;this.body.allowGravity=!1;this.scale.setTo(.6,.6);this.anchor.setTo(.5,.5);this.animations.add("moveLeft",Phaser.Animation.generateFrameNames("left",1,4,"",0),12,!0);this.animations.add("moveRight",Phaser.Animation.generateFrameNames("right",1,4,"",0),12,!0);this.animations.play("moveLeft");a=this.animations.add("attackRight",Phaser.Animation.generateFrameNames("right",5,
12,"",0),15,!1);a.onComplete.add(function(){this.attacking=!1;this.animations.play("moveRight")},this);a=this.animations.add("attackLeft",Phaser.Animation.generateFrameNames("left",5,12,"",0),15,!1);a.onComplete.add(function(){this.attacking=!1;this.animations.play("moveLeft")},this);this.bullets=this.objectGame.add.group();for(a=0;5>a;a++)this.bullets.add(new Platformer.EnemyProjectile(this.game_state,{x:0,y:0},{texture:"largeBullet",speed:200,maxTime:this.attackDistance,type:"directional"}))};
Platformer.Wakwak.prototype=Object.create(Platformer.Enemy.prototype);Platformer.Wakwak.prototype.constructor=Platformer.Wakwak;
Platformer.Wakwak.prototype.update=function(){if(this.detect_player(!1)){var a=0<this.properties.direction?"attackRight":"attackLeft";setTimeout(function(a,c,d){a.alive&&a.bullets.getFirstDead().fire(a.x,a.y-10,a.properties.direction,c,d)},4/15*1E3,this,this.game_state.basicObjects.Byron.x,this.game_state.basicObjects.Byron.y);this.animations.play(a);this.attacking=!0}this._super.update.call(this,this.attacking);this.attacking?this.body.velocity.x=0:(this.body.velocity.x=this.properties.direction*
this.walking_speed,this.animations.play(0>this.properties.direction?"moveLeft":"moveRight"))};Platformer=Platformer||{};Phaser=Phaser||{};userGameData=userGameData||{};
Platformer.Byron=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.maxHealth=userGameData.maxHealth;this.hearths=[];this.space=5;for(a=0;a<this.maxHealth;a++)b=this.objectGame.add.sprite(40*a+22.5,21.5,"hearth",0),b.anchor.setTo(.5,.5),b.fixedToCamera=!0,b.scale.setTo(1),this.hearths[a]=b;this.heal(this.maxHealth);this.maxMana=userGameData.maxMana;0<this.maxMana&&this.showMana();this.originalBodyWidth=22;this.originalBodyHeight=47;this.attackRange=87;this.attackOffset=-(this.originalBodyWidth-
this.attackRange)/2;this.anchor.setTo(.5,.75);this.frame=143;this.animations.add("left",_.range(117,126),20,!0);this.animations.add("right",_.range(143,152),20,!0);this.animations.add("die",_.range(260,266),7,!1).onComplete.add(function(){setTimeout(function(a){userGameData.money=a.money;saveProgress();a.playerDead()},500,this.game_state)},this);this.animations.add("attackLeft",_.range(171,175),15,!1);this.animations.add("attackRight",_.range(197,201),15,!1);this.weapon=this.objectGame.make.sprite(0,
0,"weapon");this.weapon.anchor.setTo(.5,.55);this.weapon.name="weapon";a=this.weapon.animations.add("attackLeft",_.range(9,12),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"left");a.onComplete.add(this.resizeOriginalBody,this);a=this.weapon.animations.add("attackRight",_.range(21,24),15,!1);a.onStart.add(this.resizeAttackBody,this,0,"right");a.onComplete.add(this.resizeOriginalBody,this);this.weapon.visible=!1;this.addChild(this.weapon);a=this.animations.add("castRight",_.range(39,46),25,!1);
a.onComplete.add(function(){this.casting=!1},this);a=this.animations.add("castLeft",_.range(13,20),25,!1);a.onComplete.add(function(){this.casting=!1},this);this.objectGame.physics.arcade.enable(this);this.body.setSize(this.originalBodyWidth,this.originalBodyHeight,0,0);this.body.collideWorldBounds=!0;this.weapon.body.allowGravity=!1;this.weapon.body.setSize(0,0,0,0);this.facingLeft=!1;this.fireballs=this.objectGame.add.group();for(a=0;5>a;a++)b={texture:"fireball",speed:300,maxTime:userGameData.rangeFireball},
this.fireballs.add(new Platformer.Projectile(this.game_state,{x:0,y:0},b));this.waterballs=this.objectGame.add.group();for(a=0;5>a;a++)b={texture:"waterball",speed:300,maxTime:userGameData.rangeWaterball},this.waterballs.add(new Platformer.Projectile(this.game_state,{x:0,y:0},b));this.cursors={left:this.objectGame.input.keyboard.addKey(userGameData.leftKey),right:this.objectGame.input.keyboard.addKey(userGameData.rightKey)};this.objectGame.input.keyboard.addKey(userGameData.jumpKey).onDown.add(this.jump,
this);for(var d in userGameData.skillsObtained)this.activateOffensiveMove(userGameData.skillsObtained[d]);this.nextVulnerable=this.nextAttack=this.currentAttack=this.previousAttack=0;this.timeInvulnerability=1E3;this.preventCasting=this.preventAttack=350;this.blinking=this.nextCast=0;this.doubleJump=!0;this.jumping=!1;this.movementSpeed=150;this.jumpSpeed=420;this.doubleJumpSpeed=330;this.casting=this.attacking=!1};Platformer.Byron.prototype=Object.create(Platformer.BasicObject.prototype);
Platformer.Byron.prototype.constructor=Platformer.Byron;Platformer.Byron.prototype.showMana=function(){this.maxMana=userGameData.maxMana;this.manas=[];var a=this.space,b;for(i=0;i<this.maxMana;i++)b=this.objectGame.add.sprite((35+a)*i+a+17.5,a+this.hearths[0].height+16.5,"mana",0),b.anchor.setTo(.5,.5),b.fixedToCamera=!0,b.scale.setTo(1),this.manas[i]=b;this.mana=this.maxMana;this.fillMana(this.maxMana)};
Platformer.Byron.prototype.heal=function(a){var b;a=a||this.maxHealth;for(b=0;b<a;b++)this.health<this.maxHealth&&(this.hearths[this.health].frame=0,this.health+=1);this._super.heal.call(this,a)};Platformer.Byron.prototype.useMana=function(){--this.mana;this.manas[this.mana].frame=1};Platformer.Byron.prototype.fillMana=function(a){var b;a=a||this.maxMana;for(b=0;b<a;b++)this.mana<this.maxMana&&(this.manas[this.mana].frame=0,this.mana+=1)};
Platformer.Byron.prototype.resizeOriginalBody=function(){this.attacking=this.weapon.visible=!1;this.weapon.body.setSize(0,0,0,0)};Platformer.Byron.prototype.resizeAttackBody=function(a,b,c){this.attacking=!0;this.weapon.visible=!0;setTimeout(function(a,b){a.weapon.body.setSize(a.attackRange,a.originalBodyHeight-20,b*a.attackOffset*a.scale.x,-6)},1/15*1E3,this,"left"===c?-1:1)};
Platformer.Byron.prototype.update=function(){this.objectGame.physics.arcade.collide(this,this.game_state.layers.collision);this.objectGame.physics.arcade.overlap(this,this.game_state.groups.items,this.obtain,null,this);this.objectGame.physics.arcade.collide(this,this.game_state.layers.traps);this.weapon.alive&&this.objectGame.physics.arcade.overlap(this.weapon,this.game_state.groups.enemies,this.enemyHit,null,this);this.body.velocity.x=0;if(this.cursors.left.isDown)this.moveLR("left");else if(this.cursors.right.isDown)this.moveLR("right");
else{if(!this.alive)return;this.attacking||this.jumping||this.casting||(this.animations.stop(),this.frame=this.facingLeft?117:143)}!this.jumping||this.attacking||this.casting||(this.frame=this.facingLeft?118:144);this.body.blocked.down&&(this.doubleJump=!0,this.jumping=!1)};
Platformer.Byron.prototype.moveLR=function(a){this.alive&&(this.body.velocity.x=("left"===a?-1:1)*this.movementSpeed,this.attacking||this.casting?this.body.blocked.down&&(this.body.velocity.x=0):this.animations.play(a),this.facingLeft="left"===a)};Platformer.Byron.prototype.jump=function(){this.alive&&(this.body.blocked.down||this.doubleJump)&&(this.jumping=!0,this.body.blocked.down||(this.doubleJump=!1),this.body.velocity.y=this.doubleJump?-this.jumpSpeed:-this.doubleJumpSpeed)};
Platformer.Byron.prototype.obtain=function(a,b){if(a.alive)switch(b.type){case "manaPot":this.mana!==this.maxMana&&(this.fillMana(this.maxMana),b.destroy());break;case "healthPot":this.health!==this.maxHealth&&(this.heal(this.maxHealth),b.destroy());break;default:this.game_state.addCoins({GoldCoin:100,SilverCoin:50,CopperCoin:10}[b.type]),b.destroy()}};
Platformer.Byron.prototype.enemyHit=function(a,b){this.alive&&"weapon"===a.name&&(this.previousAttack!==this.currentAttack&&b.damage(1),this.previousAttack=this.currentAttack)};
Platformer.Byron.prototype.castFireball=function(){if(this.alive&&this.objectGame.time.now>this.nextCast&&0<this.fireballs.countDead()&&0<this.mana){this.useMana();this.nextCast=this.objectGame.time.now+this.preventCasting;var a=-1,b="castLeft";this.facingLeft||(a=1,b="castRight");this.fireballs.getFirstDead().fire(this.x,this.y-10,a);this.casting=!0;this.animations.play(b)}};
Platformer.Byron.prototype.castWaterball=function(){if(this.alive&&this.objectGame.time.now>this.nextCast&&0<this.fireballs.countDead()&&0<this.mana){this.useMana();this.nextCast=this.objectGame.time.now+this.preventCasting;var a=-1,b="castLeft";this.facingLeft||(a=1,b="castRight");this.waterballs.getFirstDead().fire(this.x,this.y-10,a);this.casting=!0;this.animations.play(b)}};
Platformer.Byron.prototype.attack=function(){this.alive&&this.objectGame.time.now>this.nextAttack&&(this.casting=!1,this.facingLeft?(this.animations.play("attackLeft"),this.weapon.animations.play("attackLeft")):(this.animations.play("attackRight"),this.weapon.animations.play("attackRight")),this.currentAttack+=1,this.nextAttack=this.objectGame.time.now+this.preventAttack)};Platformer.Byron.prototype.kill=function(){this.alive=!1;this.animations.play("die")};
Platformer.Byron.prototype.damage=function(a){this.alive&&this.objectGame.time.now>this.nextVulnerable&&(a=this._super.damage.call(this,a).health,this.hearths[a].frame=1,0===a&&this.animations.play("die"),this.blinking=this.objectGame.time.events.loop(90,this.blink,this),this.nextVulnerable=this.objectGame.time.now+this.timeInvulnerability)};Platformer.Byron.prototype.revive=function(a){this._super.revive.call(this,a)};
Platformer.Byron.prototype.blink=function(){this.objectGame.time.now>this.nextVulnerable?(this.alpha=1,this.objectGame.time.events.remove(this.blinking)):this.alpha=1===this.alpha?.3:1};
Platformer.Byron.prototype.activateOffensiveMove=function(a){switch(a){case "fireball":this.objectGame.input.keyboard.addKey(userGameData.cast1Key).onDown.add(this.castFireball,this);break;case "waterball":this.objectGame.input.keyboard.addKey(userGameData.cast2Key).onDown.add(this.castWaterball,this);break;case "basicAttack":this.objectGame.input.keyboard.addKey(userGameData.basicAttackKey).onDown.add(this.attack,this)}};Platformer=Platformer||{};Phaser=Phaser||{};userGameData=userGameData||{};
Platformer.HelperGuy=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.properties=c;this.objectGame.physics.arcade.enable(this);this.body.allowGravity=!1;this.body.setSize(140,100,0,0);this.anchor.setTo(.5,.5);this.animations.add("moveLeft",[1,2,3,4],15,!0);this.animations.add("moveRight",[5,6,7,8],15,!0);this.animations.play(0>this.properties.direction?"moveLeft":"moveRight");a=2*-this.body.height/3;b=this.objectGame.make.sprite(0,a,"bubble",0);b.anchor.setTo(.5,.5);b.scale.setTo(1.3,
1.3);this.addChild(b);var d;b={fontSize:"14px",stroke:"#000000",align:"center"};var e=this.game.make.text(0,a,"Hi, Byron !",b);e.anchor.setTo(.5,.5);this.addChild(e);d="I will teach you\na new spell ...";e=this.game.make.text(0,a,d,b);e.anchor.setTo(.5,.5);this.addChild(e);switch(c.spellToActivate){case "fireball":c={fontSize:"12px",stroke:"#000000",align:"center"};e=this.game.make.text(0,a,"You need mana",c);e.anchor.setTo(.5,1);d=this.game.make.text(0,3,"(below your health)",c);d.anchor.setTo(.5,
.5);e.addChild(d);d=this.game.make.text(0,28,"to cast a spell ...",c);d.anchor.setTo(.5,1);e.addChild(d);this.addChild(e);d="Push '"+keymapAscii[userGameData.cast1Key]+"' to cast\na fireball !";break;case "snowball":d="Push '"+keymapAscii[userGameData.cast2Key]+"' to cast\na snowball !"}e=this.game.make.text(0,a,d,b);e.anchor.setTo(.5,.5);this.addChild(e);e=this.game.make.text(0,a,"Good job!",b);e.anchor.setTo(.5,.5);this.addChild(e);for(var f in this.children)2>f||this.getChildAt(f).kill();this.indexText=
1;this.started=!1;this.keyCast1=this.objectGame.input.keyboard.addKey(userGameData.cast1Key);this.keyCast2=this.objectGame.input.keyboard.addKey(userGameData.cast2Key);this.casted=!1};Platformer.HelperGuy.prototype=Object.create(Platformer.BasicObject.prototype);Platformer.HelperGuy.prototype.constructor=Platformer.HelperGuy;
Platformer.HelperGuy.prototype.update=function(){this.objectGame.physics.arcade.overlap(this,this.game_state.groups.players,this.hitPlayer,null,this);if(!this.casted&&this.started)switch(this.properties.spellToActivate){case "fireball":this.keyCast1.isDown&&(this.showNextText(),this.casted=!0,new Platformer.Item(this.game_state,{x:this.x,y:this.y+50},{texture:"manaPot",group:"items","static":"true"}));break;case "snowball":this.keyCast2.isDown&&(this.showNextText(),this.casted=!0,new Platformer.Item(this.game_state,
{x:this.x,y:this.y+50},{texture:"manaPot",group:"items","static":"true"}))}};
Platformer.HelperGuy.prototype.hitPlayer=function(a,b){if(!this.started){this.showNextText();this.getChildAt(this.indexText).revive();setTimeout(function(a){a.showNextText();"fireball"===a.properties.spellToActivate&&setTimeout(function(a){a.showNextText()},3E3,a)},2200,this);var c;switch(this.properties.spellToActivate){case "fireball":c="fireball";if(3>b.maxMana){userGameData.maxMana=3;userGameData.manaPotProb=gameConstants.manaPotProb;var d=userGameData.powerUpsDisabled.indexOf("mana");-1<d&&userGameData.powerUpsDisabled.splice(d,
1);b.showMana()}break;case "snowball":c="waterball"}b.activateOffensiveMove(c);userGameData.skillsObtained.push(c);c=userGameData.powerUpsDisabled.indexOf(c);-1<c&&userGameData.powerUpsDisabled.splice(c,1);this.started=!0}};Platformer.HelperGuy.prototype.showNextText=function(){this.alive&&(this.getChildAt(this.indexText).kill(),this.indexText+=1,this.getChildAt(this.indexText).revive())};Platformer=Platformer||{};
Platformer.Projectile=function(a,b,c){Platformer.BasicObject.call(this,a,b,c);this.objectGame.physics.arcade.enable(this);this.speed=c.speed;this.maxTime=c.maxTime;this.killTime=0;this.txt=c.texture;this.anchor.setTo(.5,.5);switch(this.txt){case "fireball":this.animations.add("moveLeft",[0,1,2,3],15,!0);this.animations.add("moveRight",[4,5,6,7],15,!0);this.body.allowGravity=!1;break;case "waterball":this.scale.setTo(.7,.7),this.body.setSize(this.width,this.height),this.body.gravity.y*=6,this.direction=
-1}this.outOfBoundsKill=this.checkWorldBounds=!0;this.kill()};Platformer.Projectile.prototype=Object.create(Platformer.BasicObject.prototype);Platformer.Projectile.prototype.constructor=Platformer.Projectile;
Platformer.Projectile.prototype.update=function(){this.alive&&(this.objectGame.physics.arcade.collide(this,this.game_state.layers.collision,this.collisionDetected),this.objectGame.physics.arcade.overlap(this,this.game_state.groups.enemies,this.hitEnemy,null,this),"waterball"===this.txt&&(this.angle+=4*this.direction,this.body.blocked.left||this.body.blocked.right)&&(this.direction*=-1,this.body.velocity.x=this.direction*this.speed),this.objectGame.time.now>this.killTime&&this.kill())};
Platformer.Projectile.prototype.hitEnemy=function(a,b){this.kill();b.damage(1)};Platformer.Projectile.prototype.collisionDetected=function(a,b){"fireball"===a.txt&&a.kill()};Platformer.Projectile.prototype.fire=function(a,b,c){this.killTime=this.objectGame.time.now+this.maxTime;this.direction=c;this.reset(a-c*this.width/3,b);switch(this.txt){case "fireball":this.animations.play(0<c?"moveRight":"moveLeft")}this.body.velocity.x=c*this.speed};var Phaser=Phaser||{},Platformer=Platformer||{},keymapAscii={65:"A",66:"B",67:"C",68:"D",69:"E",70:"F",71:"G",72:"H",73:"I",74:"J",75:"K",76:"L",77:"M",78:"N",79:"O",80:"P",81:"Q",82:"R",83:"S",84:"T",85:"U",86:"V",87:"W",88:"X",89:"Y",90:"Z",48:"ZERO",49:"ONE",50:"TWO",51:"THREE",52:"FOUR",53:"FIVE",54:"SIX",55:"SEVEN",56:"EIGHT",57:"NINE",96:"NUMPAD_0",97:"NUMPAD_1",98:"NUMPAD_2",99:"NUMPAD_3",100:"NUMPAD_4",101:"NUMPAD_5",102:"NUMPAD_6",103:"NUMPAD_7",104:"NUMPAD_8",105:"NUMPAD_9",106:"NUMPAD_MULTIPLY",
107:"NUMPAD_ADD",108:"NUMPAD_ENTER",109:"NUMPAD_SUBTRACT",110:"NUMPAD_DECIMAL",111:"NUMPAD_DIVIDE",112:"F1",113:"F2",114:"F3",115:"F4",116:"F5",117:"F6",118:"F7",119:"F8",120:"F9",121:"F10",122:"F11",123:"F12",124:"F13",125:"F14",126:"F15",186:"COLON",187:"EQUALS",188:"COMMA",189:"UNDERSCORE",190:"PERIOD",191:"QUESTION_MARK",192:"TILDE",219:"OPEN_BRACKET",220:"BACKWARD_SLASH",221:"CLOSED_BRACKET",222:"QUOTES",8:"BACKSPACE",9:"TAB",12:"CLEAR",13:"ENTER",16:"SHIFT",17:"CONTROL",18:"ALT",20:"CAPS_LOCK",
27:"ESC",32:"SPACEBAR",33:"PAGE_UP",34:"PAGE_DOWN",35:"END",36:"HOME",37:"LEFT",38:"UP",39:"RIGHT",40:"DOWN",43:"PLUS",44:"MINUS",45:"INSERT",46:"DELETE",47:"HELP",144:"NUM_LOCK"};function contains(a,b){for(var c=a.length;c--;)if(a[c]===b)return!0;return!1}function setCookie(a,b,c){document.cookie=a+"="+b}
function getCookie(a){a+="=";var b=document.cookie.split(";"),c,d;for(c=0;c<b.length;c++){for(d=b[c];" "===d.charAt(0);)d=d.substring(1);if(0===d.indexOf(a))return d.substring(a.length,d.length)}return""}function saveProgress(){setCookie(coockieName,JSON.stringify(userGameData))}function deleteProgress(){document.cookie=coockieName+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC"}
var coockieName="BA_game_data",dataSaved=getCookie(coockieName),userGameData=""!==dataSaved?JSON.parse(dataSaved):{skillsObtained:["basicAttack"],money:0,maxHealth:3,maxMana:0,rangeFireball:900,rangeWaterball:900,powerUps:[],powerUpsDisabled:["waterball","fireball","mana"],levelsUnlocked:["1"],leftKey:Phaser.Keyboard.LEFT,rightKey:Phaser.Keyboard.RIGHT,jumpKey:Phaser.Keyboard.SPACEBAR,basicAttackKey:Phaser.Keyboard.A,cast1Key:Phaser.Keyboard.S,cast2Key:Phaser.Keyboard.D,healthPotProb:0,manaPotProb:0},
gameConstants={healthPotProb:.25,manaPotProb:.35,coinSpawnNumber:6,coinSpawnProb:.4,powerUps:[{text:"+1",name:"hearth",cost:3E3},{text:"+1",name:"mana",cost:3E3},{text:"+\nrange",name:"fireball",cost:3E3},{text:"+\nrange",name:"waterball",cost:3E3}]},myGame=new Phaser.Game(800,600,Phaser.AUTO,"gameDiv");myGame.state.add("BootState",new Platformer.BootState);myGame.state.add("ShopMenu",new Platformer.ShopMenu);myGame.state.add("SettingsMenu",new Platformer.SettingsMenu);
myGame.state.add("LoadingState",new Platformer.LoadingState);myGame.state.add("TiledState",new Platformer.TiledState);myGame.state.start("LoadingState",!0,!1,"menu");
